package:
  name: gaff2xml
  version: !!str dev


requirements:
  build:
    - python
    - cython
    - numpy
    - scipy
    - setuptools
    - mdtraj
    - openmm
    - ambermini

  run:
    - python
    - pandas
    - scipy
    - mdtraj
    - openmm
    - ambermini

about:
  home: https://github.com/choderalab/gaff2xml
  license: GNU Lesser General Public License v2 or later (LGPLv2+)

